### ISSUE TITLE
I can't apply dagger to my play framework project.

### ISSUE THREAD

**Issue by crocket** [square/dagger#185]
The project is served at https://github.com/crocket/ZeroIrcLog
When I run the project in play and access it, I see the error below.
The source of error seems to be at root.Global.onStart(Global.java:17)
What have I done wrong?

[error] application - 

! @6djfka711 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[IllegalStateException: Errors creating object graph:
  java.lang.ClassNotFoundException: root.Global required by class models.LuceneLoggerModule]
    at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$1.apply(ApplicationProvider.scala:142) ~[play_2.10.jar:2.1.0]
    at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$1.apply(ApplicationProvider.scala:106) ~[play_2.10.jar:2.1.0]
    at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
    at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:106) ~[play_2.10.jar:2.1.0]
    at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[play_2.10.jar:2.1.0]
    at scala.util.Either$RightProjection.flatMap(Either.scala:523) [scala-library.jar:na]
Caused by: java.lang.IllegalStateException: Errors creating object graph:
  java.lang.ClassNotFoundException: root.Global required by class models.LuceneLoggerModule
    at dagger.internal.ThrowingErrorHandler.handleErrors(ThrowingErrorHandler.java:34) ~[dagger-0.9.1.jar:na]
    at dagger.internal.Linker.linkRequested(Linker.java:142) ~[dagger-0.9.1.jar:na]
    at dagger.ObjectGraph.getEntryPointBinding(ObjectGraph.java:264) ~[dagger-0.9.1.jar:na]
    at dagger.ObjectGraph.inject(ObjectGraph.java:238) ~[dagger-0.9.1.jar:na]
    at root.Global.onStart(Global.java:17) ~[na:na]
    at play.core.j.JavaGlobalSettingsAdapter.onStart(JavaGlobalSettingsAdapter.scala:17) ~[play_2.10.jar:2.1.0]

**Comment by wsargent** [comment]
FYI https://github.com/wsargent/play-java-dagger2
