### ISSUE TITLE
1.1.0 migration: "Module adapter for class X could not be loaded. Please ensure that code generation was run for this module"

### ISSUE THREAD

**Issue by poblish** [square/dagger#302]
I'm testing the upgrade from 1.0.1 to 1.1.0 (Maven, Java 7), and added the new dagger-compiler dependency as described, but all my TestNG tests - which call ObjectGraph.create( new MyModule() ) as a final static - now fail:

[snip]
Caused by: java.lang.IllegalStateException: Module adapter for class blah.MyModule could not be loaded. Please ensure that code generation was run for this module.
    at dagger.internal.FailoverLoader.getModuleAdapter(FailoverLoader.java:41)
    at dagger.internal.Modules.getAllModuleAdapters(Modules.java:43)
    at dagger.ObjectGraph$DaggerObjectGraph.makeGraph(ObjectGraph.java:167)
    at dagger.ObjectGraph$DaggerObjectGraph.access$000(ObjectGraph.java:134)
    at dagger.ObjectGraph.create(ObjectGraph.java:126)
    at blah.MyTest.<clinit>(MyTest.java:53)
    ... 26 more

I can paste the Module, if you like.

Are there any more steps I need to take?

**Comment by sharyuke** [comment]
I got this problem too.... how can i fix?
