### ISSUE TITLE
ClassCastException: com.sun.tools.javac.code.Symbol$VarSymbol cannot be cast to javax.lang.model.element.ExecutableElement

### ISSUE THREAD

**Issue by giorgio-zamparelli** [square/dagger#320]
I'm using Dagger with Dropwizard. When I run it locally on my machine everything is fine. I tried to deploy the web service app to Heroku and on the initial compile through the following error which i reported the stacktrace below.

My locale machine is using JDK 1.7 while Heroku is using OpenJDK 1.7

An annotation processor threw an uncaught exception.
       Consult the following stack trace for details.
       java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$VarSymbol cannot be cast to javax.lang.model.element.ExecutableElement
        at dagger.internal.codegen.ProvidesProcessor.providerMethodsByClass(ProvidesProcessor.java:147)
        at dagger.internal.codegen.ProvidesProcessor.process(ProvidesProcessor.java:77)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
        at com.sun.tools.javac.main.Main.compile(Main.java:439)
        at com.sun.tools.javac.main.Main.compile(Main.java:353)
        at com.sun.tools.javac.main.Main.compile(Main.java:342)
        at com.sun.tools.javac.main.Main.compile(Main.java:333)
        at com.sun.tools.javac.Main.compile(Main.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:554)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.compile(JavacCompiler.java:161)
        at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:605)
        at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

**Comment by gervaisb** [comment]
+1 for the @jponge solution.
Remoavong all "*" imports made the trick. (In my case it was `android.graphics.*`)

**Comment by srayhunter** [comment]
I ran into the same issue with missing imports on annotations. I refactored some annotations and missed some imports. Once I added the imports for the annotations, everything compiled fine.

**Comment by yogurtearl** [comment]
We just ran into this again. 

We erroneously had this:

```
import com.sun.istack.internal.Nullable;
```

Worked fine on JDK 8, but got ```ClassCastException: com.sun.tools.javac.code.Symbol$VarSymbol cannot be cast to javax.lang.model.element.ExecutableElement``` using JDK 7


```Can not find com.sun.istack.internal.Nullable``` would have been a much more helpful error.

**Comment by agrosner** [comment]
do any of you guys having issues here also use an Android library with annotation processing? It appears to be happening in DBFlow as well: https://github.com/Raizlabs/DBFlow/issues/429

**Comment by agrosner** [comment]
I have done some research and strongly think its the combination of a java project with annotation processing with an android project with annotation processing. I have filed an issue here: https://code.google.com/p/android/issues/detail?id=192476&can=4&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars

**Comment by JakeWharton** [comment]
This is usually a syntax error in the source that gets passed along. Using
auto/common's superficial validator will eliminate these.
