### ISSUE TITLE
Dagger is expecting injectable members

### ISSUE THREAD

**Issue by mjurkus** [square/dagger#372]
I have an app based on [android-activity-graphs](https://github.com/square/dagger/tree/master/examples/android-activity-graphs) example. 
Compile time checks passes, but at runtime I'm getting an exception:

``` JAVA
 Caused by: java.lang.IllegalStateException: Errors creating object graph:
    com.app.NavigationController has no injectable members. Do you want to add an injectable constructor? required by class com.app.MainActivity
            at dagger.internal.ThrowingErrorHandler.handleErrors(ThrowingErrorHandler.java:34)
            at dagger.internal.Linker.linkRequested(Linker.java:183)
            at dagger.internal.Linker.linkAll(Linker.java:110)
            at dagger.ObjectGraph$DaggerObjectGraph.linkEverything(ObjectGraph.java:271)
            at dagger.ObjectGraph$DaggerObjectGraph.initBaseBindings(ObjectGraph.java:219)
            at dagger.ObjectGraph$DaggerObjectGraph.makeGraph(ObjectGraph.java:163)
            at dagger.ObjectGraph$DaggerObjectGraph.plus(ObjectGraph.java:231)
            at com.app.BaseActivity.onCreate(BaseActivity.java:28)
```

``` JAVA
@Module(
        injects = {
                MainActivity.class,
                LoginFragment.class},
        complete = false
)
public class ApplicationModule implements DaggerModule {

    private Context context;

    public ApplicationModule(Context context) {
        this.context = context;
    }

    @Provides
    @Singleton
    ApiService provideApiService() {
        ...
        return restAdapter.create(ApiService.class);
    }
}
```

``` JAVA
@Module(includes = ApplicationModule.class)
public class ActivityModule implements DaggerModule {

    private BaseActivity activity;

    public ActivityModule(BaseActivity activity) {
        this.activity = activity;
    }

    @Provides
    @Singleton
    NavigationController provideNavigation() {
        return new NavigationController(activity);
    }
}
```

`NavigationController` is injected in `MainActivity` which extends `BaseActivity`

``` JAVA
public class BaseActivity extends Activity {
     //....

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Application application = getApplication();
        activityGraph = application.getApplicationGraph().plus(getModules().toArray());
        activityGraph.inject(this);
    }

    private List<? extends DaggerModule> getModules() {
        return Arrays.asList(new ActivityModule(this));
    }
```

What is the issue here?

**Comment by juanmendez** [comment]
You will also get the error if your appModule and activityModule both are injecting the same activity member. So maybe you start off with appModule and create activityModule, make sure this is not the case.
