### ISSUE TITLE
Module adapter for class coffee.DripCoffeeModule could not be loaded. Please ensure that code generation was run for this module.

### ISSUE THREAD

**Issue by Xuzhiwei** [square/dagger#449]
Exception in thread "main" java.lang.IllegalStateException: Module adapter for class coffee.DripCoffeeModule could not be loaded. Please ensure that code generation was run for this module.
    at dagger.internal.FailoverLoader$1.create(FailoverLoader.java:45)
    at dagger.internal.FailoverLoader$1.create(FailoverLoader.java:1)
    at dagger.internal.Memoizer.get(Memoizer.java:56)
    at dagger.internal.FailoverLoader.getModuleAdapter(FailoverLoader.java:57)
    at dagger.internal.Modules.loadModules(Modules.java:43)
    at dagger.ObjectGraph$DaggerObjectGraph.makeGraph(ObjectGraph.java:174)
    at dagger.ObjectGraph$DaggerObjectGraph.access$0(ObjectGraph.java:166)
    at dagger.ObjectGraph.create(ObjectGraph.java:129)
    at coffee.CoffeeApp.main(CoffeeApp.java:17)

**Comment by Rogerp009** [comment]
Hi.!
E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: dagger.internal.FailoverLoader
at dagger.ObjectGraph.create(ObjectGraph.java:129)
